image: markhobson/maven-chrome:jdk-15

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

before_script:
  - sudo apt-get install xvfb
  - Xvfb&

test:
  stage: test
  script:
    - mvn test
    - mvn prepare-package

