image: markhobson/maven-chrome:jdk-15

variables:
  CHROME_DRIVER: "-DchromeDriver=chromedriver"

stages:
  - test


test:
  stage: test
  before_script:
    - chmod 777 chromedriver
  script: mvn $CHROME_DRIVER test

