image: markhobson/maven-chrome:jdk-15

stages:
  - test

variables:
  MAVEN_OPTS: "-Dhost"
  MAVEN_FAIL: "-Dfailure=true"
  MAVEN_PASS: "-Dfailure=false"

cache:
  paths:
    - .m2/repository/
    - target/


testPass:
  stage: test
  services:
    - selenium/standalone-chrome
  script:
    - mvn test $MAVEN_PASS $MAVEN_OPTS=selenium__standalone-chrome

testFail:
  stage: test
  services:
    - selenium/standalone-chrome
  script:
    - mvn test $MAVEN_FAIL $MAVEN_OPTS=selenium__standalone-chrome
