image: markhobson/maven-chrome:jdk-15

variables:
  CHROME_DRIVER: "-DchromeDriver=http://selenium__standalone-chrome:4444/wd/hub/"
  IS_REMOTE: "-DisRemote=true"

stages:
  - test

test:
  stage: test
  script: mvn $CHROME_DRIVER $IS_REMOTE test

