image: markhobson/maven-chrome:jdk-15

variables:
  CHROME_DRIVER: "-DchromeDriver=chromedriver"

stages:
  - build
  - test

build:
  stage: build
  script: mvn compile
  after_script:
    - chmod 777 /drivers/chromedriver

test:
  stage: test
  script: mvn $CHROME_DRIVER $IS_REMOTE test

