image: markhobson/maven-chrome:jdk-15

stages:
  - test

variables:
  MAVEN_OPTS: "-Dhost"

cache:
  paths:
    - .m2/repository/
    - target/


test:
  stage: test
  services:
    - selenium/standalone-chrome
  script:
    - mvn test $MAVEN_OPTS=selenium__standalone-chrome

