image: markhobson/maven-chrome:jdk-15

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
test:
  stage: test
  before_script:
    - "Xvfb :99 &"
    - "export DISPLAY=:99"
  script: mvn test

