steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/spotify', '.' ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/spotify' ]
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        'run',
        'deploy',
        'erp-ui',
        '--image',
        'gcr.io/$PROJECT_ID/spotify',
        '--region',
        'us-central1',
        '--platform',
        'managed', '--allow-unauthenticated' ]